### ISSUE TITLE
How to use this git?  

### ISSUE THREAD

**Issue by quxianjiuguo** [JianghaoWu/SIFA-pytorch#1]
I am interested in your prominent work. Could you teach me to use this git?

**Comment by JianghaoWu** [comment]
I have updated the readme file. Please refer to that file for dataset preparation instructions. If you have any other questions, feel free to ask

**Comment by quxianjiuguo** [comment]
> I have updated the readme file. Please refer to that file for dataset preparation instructions. If you have any other questions, feel free to ask

thank you, what is the cuda version?    I got an error in running tf_to_np.py.
![image](https://github.com/JianghaoWu/SIFA-pytorch/assets/72400883/0193542a-28c3-4b84-bd60-3681f7d3343b)

**Comment by quxianjiuguo** [comment]
> I have updated the readme file. Please refer to that file for dataset preparation instructions. If you have any other questions, feel free to ask

I used tf_to_np.py  to process the MM-WHS 2017 data.  Why used tf.reshape(img,[256,256,3]) function?
![image](https://github.com/JianghaoWu/SIFA-pytorch/assets/72400883/32e2d6fe-2650-4d2a-b1cf-b02ec0fd1be7)

I used the propressed data in train.py , an error appeared. Could you help me?
![image](https://github.com/JianghaoWu/SIFA-pytorch/assets/72400883/38f229b1-96e3-4b77-b76d-6df2c38699e2)

**Comment by JianghaoWu** [comment]
Your data dimensions are incorrect. For 2D image inputs to a deep learning network, the dimensions should be [batch_size, channel, w, h], but your input dimensions [8, 1, 256, 256, 3] are obviously incorrect. If it's grayscale images, the channel should be 1, and if it's color images, the channel should be 3. I'm not sure where your data comes from, but I don't recommend using tf_to_np.py. It's an outdated data storage method. If you're dealing with medical image data, simply preprocess it into [1, 256, 256] and save it in npz format. This way, your input will be [8, 1, 256, 256], which is correct.

**Comment by quxianjiuguo** [comment]
> 您的数据维度不正确。对于深度学习网络的 2D 图像输入，尺寸应为 [batch_size, channel, w, h]，但您的输入尺寸 [8, 1, 256, 256, 3] 显然不正确。如果是灰度图像，通道应该为1，如果是彩色图像，通道应该为3。我不确定你的数据来自哪里，但我不建议使用tf_to_np.py。这是一种过时的数据存储方法。如果您正在处理医学图像数据，只需将其预处理为 [1, 256, 256] 并将其保存为 npz 格式。这样，您的输入将是 [8, 1, 256, 256]，这是正确的。

could you tell me your email or other chatways?

**Comment by quxianjiuguo** [comment]
> Your data dimensions are incorrect. For 2D image inputs to a deep learning network, the dimensions should be [batch_size, channel, w, h], but your input dimensions [8, 1, 256, 256, 3] are obviously incorrect. If it's grayscale images, the channel should be 1, and if it's color images, the channel should be 3. I'm not sure where your data comes from, but I don't recommend using tf_to_np.py. It's an outdated data storage method. If you're dealing with medical image data, simply preprocess it into [1, 256, 256] and save it in npz format. This way, your input will be [8, 1, 256, 256], which is correct.

could you tell me about your email or other chatways?  Thank you

**Comment by quxianjiuguo** [comment]
I processed the mmwhs data to train, but I got an error .  The numclass is included background?
![image](https://github.com/JianghaoWu/SIFA-pytorch/assets/72400883/491707e1-5a9d-4fde-9395-8a33f09e093d)

**Comment by JianghaoWu** [comment]
Yes, the class number includes the background. So you should set the number classes to 4.

**Comment by quxianjiuguo** [comment]
> Yes, the class number includes the background. So you should set the number classes to 4.

what about the cuda , tensorflow ,torch version ?

**Comment by JianghaoWu** [comment]
CUDA 11.4
torch 1.8.1

**Comment by quxianjiuguo** [comment]
> CUDA 11.4 torch 1.8.1
How many epochs of convergence did the model run?

**Comment by quxianjiuguo** [comment]
> CUDA 11.4 torch 1.8.1

could you share the preprocessed MM-WHS 2017 data?  Thank you

**Comment by JianghaoWu** [comment]
I am not the author of the SIFA, and I do not use this dataset, please ask the author for the dataset.

**Comment by lkfiean** [comment]
你好，可以提供一下图片和标签转化为npz格式的代码吗
谢谢、

**Comment by llkk2019** [comment]
Dear blogger, hello! Nice to see the code you wrote! May I ask if this code basically reproduces the official open source code of SIFA's paper? For example, the details of the overall framework, the number of network layers, and some hyperparameters. Looking forward to the blogger's reply very much, thank you!

**Comment by miniMuggle** [comment]
> I processed the mmwhs data to train, but I got an error . The numclass is included background? ![image](https://private-user-images.githubusercontent.com/72400883/269902383-491707e1-5a9d-4fde-9395-8a33f09e093d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MjgxMjAsIm5iZiI6MTcwNDYyNzgyMCwicGF0aCI6Ii83MjQwMDg4My8yNjk5MDIzODMtNDkxNzA3ZTEtNWE5ZC00ZmRlLTkzOTUtOGEzM2YwOWUwOTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDExNDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ODViMjZkMTJlZTA0ZjU5ZWI3YTIzYmNhOTA0MzMyMmY4ODQzZTcyM2JjNjEwOWI4NmZmMDk5NmRmNTFmYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bod7lG5Dvui4sz98GzTOulFB2t8imXtdaLy-oYJ5mEE)

Excuse me, has this issue been resolved? Could you please teach me?

**Comment by JianghaoWu** [comment]
The provided code is nearly identical to what you need. You can utilize this code as a basis, and kindly acknowledge the implementation from this GitHub repository in your footnotes.

**Comment by jingluo-lan** [comment]
![Uploading 1717429019876.png…]()
![Uploading 1717429019876.png…]()
![Uploading 1717429019876.png…]()
![Uploading 1717429019876.png…]()
你好，这个报错是要怎么解决？

**Comment by jingluo-lan** [comment]
Traceback (most recent call last):
  File "/home/user/lanzheng/CycleGAN/SIFA-pytorch/train.py", line 93, in <module>
    train()
  File "/home/user/lanzheng/CycleGAN/SIFA-pytorch/train.py", line 65, in train
    sifa_model.sample_image(epoch, exp_name)
  File "/home/user/lanzheng/CycleGAN/SIFA-pytorch/model.py", line 174, in sample_image
    save_image(denorm(self.realA), '{}/realA-epoch-{}.jpg'.format(sample_image_dir, epoch + 1))
  File "/home/lanzheng/anaconda3/envs/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SIFA' object has no attribute 'realA'

**Comment by JianghaoWu** [comment]
I am not sure how you rewrite this code, in my train.py, there is no line 93, and line 65 is not sifa_model.sample_image(epoch, exp_name). self.realA is introduced  in update_seg and update_GAN, making sure they were ran before sifa_model.sample_image. And I can't see your loaded image.
